
def rotation_calc(input_1):
    #Suggestions generated by ChatGPT
    result = tuple(b - a for a,b in zip(input_1[0],input_1[1]))
    return result



input_1 = [(30,60,90),(0,10,15)]

print(rotation_calc(input_1))

