input_1 = [(30,60,90),(0,10,15)]

def test(input_1):
    #Suggestions generated by ChatGPT
    for tup in input_1:
        result = tuple(b - a for a,b in zip(input_1[0],input_1[1]))
    return result


print(test(input_1))
print(type(test(input_1)))

